apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird
  namespace: netbird
spec:
  interval: 1h
  chart:
    spec:
      chart: netbird
      sourceRef:
        kind: HelmRepository
        name: helmforge
        namespace: flux-system

  valuesFrom:
    - kind: Secret
      name: netbird-secrets
      valuesKey: authSecret
      targetPath: server.authSecret
      optional: false
    - kind: Secret
      name: netbird-secrets
      valuesKey: ownerEmail
      targetPath: server.auth.owner.email
      optional: false
    - kind: Secret
      name: netbird-secrets
      valuesKey: ownerPassword
      targetPath: server.auth.owner.password
      optional: false

  values:
    server:
      publicUrl: https://cloud.lxft.dev
      config:
        extraYaml: |
          exposedAddress: "https://cloud.lxft.dev:443"
      disableAnonymousMetrics: true
      disableGeoliteUpdate: true
      image:
        tag: "0.77.0"
      auth:
        issuer: https://cloud.lxft.dev/oauth2
        localAuthDisabled: false
      service:
        type: ClusterIP

    dashboard:
      enabled: true
      image:
        tag: "v2.91.1"

    postgresql:
      enabled: false

    database:
      mode: external
      external:
        engine: postgres
        host: netbird-cnpg-rw.netbird.svc.cluster.local
        port: 5432
        name: netbird
        username: netbird
        existingSecret: netbird-cnpg-app
        existingSecretPasswordKey: password
        sslMode: require

    gatewayAPI:
      enabled: false

    extraManifests:
      - apiVersion: gateway.networking.k8s.io/v1
        kind: GRPCRoute
        metadata:
          name: netbird-grpc
          namespace: netbird
        spec:
          parentRefs:
            - name: kube-gateway
              namespace: envoy-gateway
              sectionName: https-netbird
          hostnames: ["cloud.lxft.dev"]
          rules:
            - matches:
                - method:
                    service: management.ManagementService
              backendRefs:
                - name: netbird-server
                  port: 80
            - matches:
                - method:
                    service: signalexchange.SignalExchange
              backendRefs:
                - name: netbird-server
                  port: 80

      - apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: netbird-server-http
          namespace: netbird
        spec:
          parentRefs:
            - name: kube-gateway
              namespace: envoy-gateway
              sectionName: https-netbird
          hostnames: ["cloud.lxft.dev"]
          rules:
            - matches:
                - path: { type: PathPrefix, value: /relay }
                - path: { type: PathPrefix, value: /ws-proxy/ }
                - path: { type: PathPrefix, value: /api }
                - path: { type: PathPrefix, value: /oauth2 }
                - path: { type: PathPrefix, value: /.well-known }
              backendRefs:
                - name: netbird-server
                  port: 80

      - apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: netbird-dashboard
          namespace: netbird
        spec:
          parentRefs:
            - name: kube-gateway
              namespace: envoy-gateway
              sectionName: https-netbird
          hostnames: ["cloud.lxft.dev"]
          rules:
            - matches:
              - path: { type: PathPrefix, value: / }
              backendRefs:
                - name: netbird-dashboard
                  port: 80

      - apiVersion: gateway.networking.k8s.io/v1alpha2
        kind: UDPRoute
        metadata:
          name: netbird-stun
          namespace: netbird
        spec:
          parentRefs:
            - name: kube-gateway
              namespace: envoy-gateway
              sectionName: stun-netbird
          rules:
            - backendRefs:
                - name: netbird-server
                  port: 3478
