apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
    namespace: netbird
type: Opaque
stringData:
    oidcClientSecret: ENC[AES256_GCM,data:BKneJl346XX211Lv49VPmla89WuEQbO85uJoY0LoRrj4YVUIoOjb7ZTTj6YhWSQChWEC/24R6oaomakAlV90g64MDqe/GCgC,iv:Dn1fI30ruG6RgaYJHzX/c560z1SVzy5IWOH9RBcrQQE=,tag:96f25x9GnKSKbrZZdyChNw==,type:str]
    authSecret: ENC[AES256_GCM,data:ZxBS7JlPvc2d5X2nFaX/U+oPMmHxx2igUNeNs6X5oUy1u0Q98XQ4WzN6ueA=,iv:9z1urlCFbZKc0Y509yRufuyFcip/4dYHAdySj0kgl20=,tag:nbRzZqbIbHi3X8uLcnfdHA==,type:str]
    ownerEmail: ENC[AES256_GCM,data:Lq1UhgTyMM5wzsaae4xhgg==,iv:EG0ltu5glQqG5RrebzFHVKBTcdwnKptRJpIl2VCPVC0=,tag:tJHSJ6I7oHeQkuYk3DFuWg==,type:str]
    ownerPassword: ENC[AES256_GCM,data:hCVcwtS8xRZnOorPYz0Pyij/hYFxW4tVbElaIqFPPWwSrGAJ7osxB6MBa6w0PRLH21B66IQtWUn122IM,iv:w3JlJ0zMDrRm5snjfURjjDngrtvydrWLk/Z7ZS+zERQ=,tag:DGuhUvdezqud8iU8fdSnCA==,type:str]
    config.yaml: ENC[AES256_GCM,data:iNjTdu8VnL4PoQfjA4lusPgDmja8YVNeIzYvWuHsqWtHtGfDL5MbGGN0twP+TURaCCEU0D47MPpFlAzpKbMEe32KEEvCS6tqogbUeJED/3nsssNB4vr0scwU0K5cY/x5WgIeVFakZkZgO3CT2dxtZvBy/NuZrznF4xId1DZlB4D0fcVhszHjmm2v4DX6rzr8evWWds6hb09psswUW4wvf+8HasUTfoUtNic9MmXL5wSESS+SAljY2fR5xu92FmT4fGOjCIQwvU2oVCGgkd1k/YLE0Pr4XUd1ocRTZmMoRLIg09I55Wv6mQ8iM8uZ86BWz90XzBML9782wewXP7A1mfVGj9pEbnmg+dxHVm6AF1Qz2PALE0o6m2bmrj/PytMJ/R4Oau6Cn5nQxWZtUtGL6KJZl8fBKCAofIlU9cRtQIQGiBmFBjCctawet49Oi5E3kTy8DqSuy8uCzr0UxVzeyPFzg6PiYnXBI52z59qDLHCn1KubQOAyIAGPkAsm3ii5TKNZ7UsV29rWgNakUuNs4WvoiGOnCMWHCkzrV7YzpD1vBt+PH5AwGZLA20nx+jsNt5rYEcGTKaW2MgNKIqttQiA5a9muZK27pPM9lMHO4hGTZ5Ww9z65HjTbbdRwxwXuEMmYhXwFByBrt7qkA+2ST8EhcTPPhmJD46KgIIYiNcsM7mlT0QzHNvoHGgNW5y9etVHweCCCk2TGKvFpk8WhHqmpLJbg5rgdDKWsPCWJikne+C7P5vRldnFJJVOdq/oetzyy3wepBnXlvwqc6VYnQXtEc3Hl+XOcPs+8ChCYcAzIYXQz1xQ9rjxWSWfvjEuWKY1uHJ0HLQTvSkbnjAd+HCHkDw2aXRv+gLorYOEhoYv5d3HAUY/5ApP8rsQfW0B5nkUCQvVCbBlFMAk4W7+In94NEHkWgU/2ERUn/2vNz3aduJ6qk4jhtfQP2a6TMVuxcvdqzKx/NrFS78nz92q/bIqpa747sQxeXBjVEkvsGS3H6SJ1EIVOkAxPVoGQyfQU1poSuw1NhKD/38Nib1HFm+MXTLQDRmJ9eLQljcUNr7Do27Ei586hCgRrYTpRuGBHSBHSIGO49GOnsALDsHGnnPZ7mmx0JIAYUGEm8qhNtD6ZJQTMHp04s3t9tVmjKo98fGnOei4VYsJF8YmqDNQAh22c1cSPhLwstzMr8ElPOEClLo6hgVmLmAIWntxVykmKoaPkAHjwVBDky8mxwbX9tdJNRDApHiqPr3TwndWeb/Kdo4Qw9IPsu8/s2hTxkmrEr5LNkKQdT1h1kw49i+eb967Db/lgqmuy,iv:8Zg2QeXTTWSsd3iffbM+OXKau2ZvtIv5Wfw2ROpWbko=,tag:TDRcYb1WfyVZElKLwYuHWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZE9DR3VtNzRUOXA0RDBq
            MHJsa1NVMGN0NkJjTHI5YVpVSkRPeU9VVFR3Cm9ZV1BPblZXczFXS1dtYXNWWWg3
            US9HaldySG9XTlgxaDcrN2tPdW14VmMKLS0tIDk2dGRkRFIrZklIdVZ0OHp0ZkVG
            bXlNM01sMzhsNHJQS0dEYzhzZ0ZWcFkKe8X7sWX/yViOK4VamqPyFfLBtgxZsiFp
            T+fWg2ipGDayB1scQYUmSQQ9y79lEZ7bXatZIFOUUfrRuQXWte3drQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T20:56:20Z"
    mac: ENC[AES256_GCM,data:jqnKZmquQO9YeT4XeACop0RrXiroIAtT+ADPqBjxBcoBDvB5oQoVBYy8Knjdf1KQ8sOh0yL3sM2VfiE2sjKct0OKeohvSx8oBuPd4YZaRXFe++/S65CDwP1GQltm5JF9MyK2tFzVlfQ8nbKdvn0DRdwXzo7NJ+zQ/y19dLq/RvM=,iv:geIoav4fgzaR7rGWq5wJOkCIeuhdXF2G00AR9CSna/Q=,tag:JMyrT6U9J4AK63VPNvXq6Q==,type:str]
    version: 3.13.3
