apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
    namespace: netbird
type: Opaque
stringData:
    oidcClientSecret: ENC[AES256_GCM,data:iGj5sfeI4lA95AJWf2N9O08ALjLeysDKaOKQv5WQHcJjhnQRizZhU0bbDn5AdP7q7/PNMEp4Q0M3po0nTAOBBbY4TfKeuyCb,iv:4r8J+WiElQY4op3dTb4v/iU73CFsRgG2EPKrX42YwYs=,tag:RTO4cNzrNb43mE3DId02BQ==,type:str]
    authSecret: ENC[AES256_GCM,data:ydkHvF8p+84giNomGx/mgTwfj3XfvnXPuny5g/OK+vuvxRHKdzVfqnEa8dE=,iv:hiJ/kUlxlyclgwcZwoi4KRSpszNg9M4wsMqATNtyNN4=,tag:qWWrQuQ6Upjyr9jgxo+d4A==,type:str]
    ownerEmail: ENC[AES256_GCM,data:bNH4JytLCvu5eB5TezPs6A==,iv:nABnf870JJ6XL94JY033OICyzdMnOiWMJ+wj1boiP7g=,tag:0sh//RGZt6DY+YDpiQhjqA==,type:str]
    ownerPassword: ENC[AES256_GCM,data:a9TFrfa3palU3/67NPyrraA82VrT0blug9haq1cx3VO1BLxATi72moVNwxjK9HJ9u+uTxYam5DCdNGN7,iv:PAFlQAcXFddlazb1b/TFm9DQpFxP3RgyidobYxOwbzw=,tag:mZD/AigysJE/byuLj+hBEA==,type:str]
    config.yaml: ENC[AES256_GCM,data:AYmgDSJWenvDe4phYMsKUJtX797GhnE+DxjxXk1FUYspZmFiaK7opwXyog2sW7SAYAT5HxvGi5zf5RdtXwtjxQgKi+8YveCJXqotJcvhdbRlB9Bd7Bk6uUgjIdq2UX6ewLHC7o/mcfabWuD3CpGq37yVJdVcLJZstUrLPsT/32Nf/BKA6uY3fz/jo1f5+CreY3fcVFtSH6P0BdGRM2MzQrpa/WPx5LsX20G+Y1FCkS42US2MMWZg+PQOV9qsZCaREsIWz6pERP9BZsIkTB1VEUiKEcFi4OmZt4A4lFvi1XbSBJqzkbhH7ZS6wKu5F2EICH3txBWsRhBiueSiz8RyrqXZvCKZEwJJ0t7kP2FFGmddw8/SIdoIn/JfQAoUzT/Rg22SQWcKSQdqmLS4jjNeBvySY/iLDusLzpEO2lD/pwbAIA6Q61+qWUZhjEDat3URoQQoZdXs84RTukfLV1s8iQB6Cb5nNPWUT9/SW0r7JyRtdOrtEQgUGWP7LlZLHHrv6XOfRJpO3g5Li+FNl5SOiA0C6d6qkIFDOQKMkXaqtV2U+Zs4DhslHi3O6MzEUZQ7uUa8sLPevMMjb+svUmQdjVfHHD+F8usVQCVQ7z6RXfNBwgvt7us//50YTNDvLcTNq8qGJs9WSDg7x75xclDv39PLOkzvQtSsUwT7wAq9kOFHHPnrykPXUj40yvXAOd7eXKIfHY6O48LrtnNWAJ6xF2mNm0V7YE/C+jGfcbOYGbd8VlULhmio04lCJGxGpy4eYArNpoJCzzzF9v8Rlhdg/hgiUCEvAPCVFhEaP/ZpFqxRxqu3md88g1UCMNUhYm6te2TRliF18orxOOTNJg3yotZcEh42ROYDMbo4tP7MRAq5LkP9Szq8bOC2jkQt5fDPbl5sCSadHkc+1vjOlQBGzwDSfBcd0NxCNwBsNeufWQyxkfeZHLW8ul1gCtH9TITNBvi4r1vKVCfMcesz+Y4tL2HflbqVnR0Wcx0QAVKpntldRzvnOdIgSMpv+u0mpoCqIgxD2XX9TXL/iomPKJ98TTdbKC/Y0J04e/67Wj71P2M3hxdPXypQooKErFBWp+FE0PC1T2cMKZjxeh6+TwBOY7Q9nYeLC4Pra/PYy3mRi+8vQzucHJsVswA51KoNNQ==,iv:W88+4x2fYLX1qluU+7WX+GxYbDSBTU7EymMMJo/bZMo=,tag:C3PwJf/yJeRWSWvU6b7PuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT2lQeERRYXhteDJua2R2
            UUhqSzE0a21GanpBSVhKeTg5VmZwZXc0NEJZCkpaQzJMWS8ybGlZcDg0bE41SUFu
            VVpoN0g2amRUeUtYVitpd0JIMHFDOUkKLS0tIHdNdnlkMENiQU5jZ2prZ0R5cXp6
            Q2N4MmhxcTFzU2Rteno4bWJDV2lmcHMKwAWw8zj1ZAV88D6yCn/iTNfMM2/dAeJF
            ERHE+2DAQk53/xEI9gP+D+xHUNjq3pNg6oIGtAlUD26IpQ+nsx33tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T23:06:02Z"
    mac: ENC[AES256_GCM,data:8xv5BXN3bjNJTlqRACOcUbdoK5YNVtzH81nTY38IFFCfEVdRoPfojTNEbFsU6fWkJBc9g4d8VL4J7ll4Skk+MQzTMfmE0vHJZHL6qJPB2LSBVjmLyV5nqnS0MeZEe1XlwB1QgBLmuDqi7qA5GO6nh3UgikcS1YWhNzGH2KzuXa0=,iv:klYaQUwt8mtQNlnqw2F6r8JPCglWd0jNTsgbMtAoTn4=,tag:5nBoldUKh8fhWYtYRyUTJg==,type:str]
    version: 3.13.3
