apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
    namespace: netbird
type: Opaque
stringData:
    oidcClientSecret: ENC[AES256_GCM,data:9JJ7oouPFHNCjrTgJs8yKANnz23AP8hFUjYLfpWq0//iQ6M+gXZ1ubTvmJnAlHFfzW1dIQt6TGmvIit/3vJeNZ1mT2xeRN4B,iv:tiy3LxRqHvs2PnlTVu+GZdZuoCrz9lwl5R5bOqk02h4=,tag:VDllQ1yxoaMIdt1cbEmSSQ==,type:str]
    config.yaml: ENC[AES256_GCM,data:MSNtaxoDUeXzQTwpyfLpTO5hBCK10/7G3myIfHTrTNfHxiVftPF35vFJhoTdw/FOqHKr3mqQorzn09jxJz4Ubvys2Q8U4iZtL/coGQ1MheaJI9pc8tG0y6ZCEMnykNl2/2kxAGcr86lcrL8re8edtfzAvxmZcYhBU16ryIaZfZMrfX6WdOFT+rJfu8swTihk+GTv95Oxqyo4mJsx1HxYUxxdVAAcBW3OpjTKB/jwS4YeF2Cy26zt3YZyG4XE/l+kpRN1SJYTKHEOMmDzbdrR/SEmGJtN/LqEMuw89JZoEysAiEIT7nwV4G4r/vUsWqc+M2yKwgNnefwu1vYuBA78OtEvkAMqOy9FVd8f1fUk7nwBS99ZkMwWTkI3CRDG9InAaQuse2fWzkHwufD2VlbHRBhNW8pRX7hQS6t+JUacnyX11LmxyAAZZenYkr0ZyyJKhBwZd/BbV8hk75vD5V70BC3HJRs0CoFHppW+xfocgp+fLEHvB89ibYvZZLDSm2rWcHwLQLA2vbybESqZsnp+eLM+doiH/HNy9jln0np9B4hifD/gHqpehoo4dNHjSX085RKhDN2J7CkLTnMN9j2kVrwD6WrTOvNf3+3ZKqJokQH27igfZJLTwe5aJSTZsGxqYOvvdJs0quqDS6XYg0G5TruFGU26d8AVjZboM8VFnovaD9zrxKPRmfD3BSgJDvb0+7l+zjw2AMH1qeJohocd/pfNZ0eyaYY6GZ+9E7y2bI0C6PZ65WIUTOF1yYiV4c6FXFbXMI012L9RsJYFHKftxDEJfuW3US7xn0yn3PzHhWymXOmepxWuhfWcr05VNDGFOM6jQW8Z3fT8Do+C+6+58cakevy8gLMLYvW8hx850pMq+e6GjmRaFwRA0fvFzWAfG7HIGvTr+MIMuqxmzoBojuu8/bF/2TbPXW3qd6NaTvd+OafNMxMcNC6ztVIS6YeZFuGoYbS7Ae8E8H+Z6jF6N8Gte34XU5Cpdk/RR9xpwB829aLTm5nVsdBgSRPjpN0FmlSqiAPlhMqLEJEQMpNpUymJspM3ITPCjZc=,iv:jRrtUbvKnNxImCy89skNRTGuPKi0hqEJSn3oSPciVPY=,tag:+8raR2SRVns/WVK0mOXxBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRjgxeWppeFB5WHJDaWFS
            YTdqY3d5MGk2cC9FZ2xZWnMweTM4NG9KNVc0CkV5QVJwOW9qcTRaMnVzVkZGTnpD
            YUhjR1ZrVWRYMllFTUtLK3F0N2VsMVUKLS0tIEJWQTFYMm5sRXNrbjQ1ZjdwS0kx
            WnI5WVNGSjRkb3ViOUh4SUl6Y0NZS0UKRB/BRhnc81UcR54DrMnUc5PuC6j2EkbU
            StcyPH9vvZEE8ynfI/wdSGla26TuBSJRS4l5Te29QtpDrSUI+pyz1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T07:26:41Z"
    mac: ENC[AES256_GCM,data:zlmv7LN8UTIqjMm/6vfqPGBIcC6tIjzcqsps0LOEd/aJsi2cPoxAYz2xJaAmSR3uK2uzyZuhGwnGLmuZF9q+ox2T1FpX6tKnKzbzUQeaUV7PvApa7zKpc4EDk6MUASfId6OuadQQk0/lzN4/j16/pD+HpKQz7mZucuQfMEyjo8g=,iv:wPLt33BDT43ZFLynKYKgsmmZd3US/Ltne0NqM6Nl6dY=,tag:eSVGWJR5hT7t/Fg84hMRBQ==,type:str]
    version: 3.13.3
