apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/guerzon/vaultwarden/vaultwarden
