apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-oidc
    namespace: vaultwarden
type: Opaque
stringData:
    SSO_CLIENT_ID: ENC[AES256_GCM,data:ArOmNRjGzoIiu0A+5/dPYuCVB3g8LCIhxfPnnaQ3VOJFZl5ikCfu1bTK5NN9cWvkd2h3o2NTSiaEkJrn7rujRUsPrLKM0+tW,iv:HISoVFbOMFI/FufdcyGj/R6b/9exPGe/06k+7k85j9c=,tag:RncUfBQBZVX/heHcsEpKMw==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:VGorILIPfHgkKTURHpK7T5XfaFDnW9QR7ALa8IkO1RZ88cKw39/hGCZyBFZACZrBNmjYPVAI/vvYh7hScidrFo0zJn2PMuQk,iv:IrGd1q1T52CWNpJvZbrPRbz5SdyPOjJeoWeeORqe3kM=,tag:0ItG5S5DvsJal7T4InQGXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVnN2L0lDKzhQQTRWTE1x
            b2xKMlA5SWJUTXFuV1FwaHVEdm9rYWFKWWlJCjMxeTZkN0hEUFdXbUw0eW8wUVRi
            cENnVDZ4dStzMjdEdWhMZkJYNXdYL3MKLS0tIFFHSi9KcXowV2dwY3U1eXBlQ2FL
            YzRrcEFpSDVocURjejBhNHlkRHJsWWMKvrfqjXhr33kZvw0NXIQU+mjArgYAKzTo
            2qZFgz9fMw7k/1kJs2XXoBIAsITi/ADKV3HVhaIQjJ1YhSgZ1eLX2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T11:35:16Z"
    mac: ENC[AES256_GCM,data:sDsvpBaLh1ooOYdycFA5HK/NruVBNhnAx4bRpfMNhQi+Z6NpjntNYsyqMhks5c0ZeltIgx5zKJ/ldSN6Fr5EvSJZeOu9zvGb0IIEpBQJG8CFs83e6LljATLlfgkLjjPTaXdYm3zYhEdB8aqshCBdGf6Ay7wgbuYAgyCRYVScofE=,iv:aoEae/dy63OyjV/6iG5zASREg4EpglD3+xeQP0AvPKc=,tag:wsMHwVn7JQZHy43hNZQNDg==,type:str]
    version: 3.13.3
