apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-oidc
    namespace: vaultwarden
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:ztwz1JLJ9QRsSp3lqdOeH4RjonGDkl3wwDpINbh/vk9QqcAIqR+hH8Sb+PGk17RulDO6Uisuoap1404QueyIWwqZwp3kOOeA,iv:7x+r3YAexMCu7TXkZ2ld4q3v/9GS2kEl8LWGlbJh0Gs=,tag:lkjaFTMYcOr69PTxpvLQ0A==,type:str]
    clientSecret: ENC[AES256_GCM,data:wUn/DTA/KoW87o6iLI99SutQSl2gmHsvilPtl4uDNsAIV+cD7vqQTnxjFmcYtfwJQDQ3G8IxgAbxiNl3FLz+EZ9uyUJP8Sfb,iv:iZiKQKcrt/eDtcbV9unYsTU9kkrdTv6P7v+4ERJSSWY=,tag:Hw66rn8pEtl0VKZu7rYGNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveDQzMW8wdzRlb0t5ekZr
            OWxHd2FEVG9WaVpYKzltMGRvbXBxNCtHMmpVCm5RWElDSmFEZTUwM3dDcHNsUlFm
            clBFTDY5UkJsUHkvZVVLclFnOVovN0EKLS0tIGt0cmY3Y2p0R3hxQU9TcnJlcmUz
            bTl6aW9tMk1haGN6b3NWWkh4cXNmUUkKJixR3i0OAmUk+4xcymoDFh1wE3/CZlFg
            KdCfQj4bE+LEr/gU4hY/ajumpjSq3+y94b8ALFOUku3Dfmszw8eImw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T12:12:48Z"
    mac: ENC[AES256_GCM,data:5Mhdf+yNQa75UDZ0XcaXUniHw6p2uolAfUfaJXHJdMsE48vpZEIYvcfUUYoDGeaiRQHNSLeMjc9mnI/b5qU/uPuD0jDRnF23TDurr3hI9voVoztgiTOwjYol22pnrCRb9bPqcyWqxx3WtlEwvhTI5zdF29tc/UFNfVU4l5boae8=,iv:RM0PMTZ3o8ijxbhgHtEEUlMbaNVs5pEducuKso6uw1k=,tag:argaJmhVP+C7a8FzaViTRg==,type:str]
    version: 3.13.3
