apiVersion: v1
kind: Secret
metadata:
    name: netbird-reverse-proxy-secret
    namespace: netbird-proxy
type: Opaque
stringData:
    netbirdProxyToken: ENC[AES256_GCM,data:jeWpVUZJqpVuGYNGv8suIOouOMgw6VTTHQ84L0Y6MG54GGBJsYIKYg==,iv:cthin7m7H6KesGJ3yzxov4QKTItzCqvhlf4RRMJ/tt8=,tag:/TZmRheVg3Twfo9pl8Sg5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbTJiZWJjVW9PbExGN25K
            a3hMdmd0a2JSU083K1Bmc1pNbDkxYW1yaWxvCjhTOXlKTXhQZWRBQnVkbmF5S0gr
            Z1JnZFBBbU9lL1hSZGhlQkpZK1JKancKLS0tIG9YN0xSWmkvY0h4ZEdyZEVTaEhP
            MG9HbG9TRDhhTkFqNzhiQ1ZKZUIxRkEKxzV1akih/DqVNfDuUNjtVYhMfkkYKl8T
            56T+LiefFjfVKQlK5La5HfdYOVaTwilwGg5qLzXzqMVbvLRitQ+5bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T23:09:28Z"
    mac: ENC[AES256_GCM,data:v6BczRUKx2f4w2//xJpXgVwr9DZTAafC9/EGQ/P5MdOB+TfyZOuM44fBwyPsqr8N7KrnM7yClO24278dDNry6NYQdH5A7FC7HHk8OM/N0yhYGgaTyynZ/U1TefeMCC16k/M6I1ef/fLXI52soacv9cj+NUv4KVMOc6Mmvj3QueE=,iv:kDPHQSi7YbarFrNx4wNlkGaU79R7LNwLGHuK4C+b4YQ=,tag:KZbA7oG4HjAvvaH09uubDg==,type:str]
    version: 3.13.3
