apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: envoy-helm
    namespace: flux-system
  values:
    deployment:
      replicas: 1
