apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oidc-secrets
    namespace: forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:HfFyqVPHx/kbAaUVbE/z3lMs+6bbCa6fmFxRy+tuRtJB6tMMVxMzbSeKmN/2dVYmhC/246Qs5xFFONWoezfseVshTyiTd1Du,iv:js1pvqbGVcVLa8FtFc8BYEDHyLnUcQwQG5RC9+EwtS8=,tag:zOSqRDVR2a8C9Hj5uox/jA==,type:str]
    secret: ENC[AES256_GCM,data:0qAe86Y26Gl2I8YJPE0+Y/1U7VYb0qMRE8Z7zEbWxaX68sYaCvkhfH9IR3zBpeSRgjHSw8CEJfIkIlA/2VULTQsPn5NIgLyE,iv:6IgAQsXjNIpCdQ+86U+KRsc2EkvxDko3C17KskuMbVs=,tag:u6w65ziuvueF6Hnk5DZFHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSGpNcThPdjFhOU9kQVky
            Ris1aWlNTHQxRjRjTDA0aENoUjcrdTJmMUVrCnhGTm5XQjFRcEpvTGIwSzMwV1M0
            ZXpKbGkyZXRzM1Mvcm5PeEhkYkdIN28KLS0tIDZIS3J2SG5oMkpxQXpkVTJteGY1
            VW1wK2FBNjc0Um16dHIvbEpjR3huZHMKlF3JAjXKN3iUfCjndjaOnTRCmzhz5e7h
            0FRp/KODVeFPcyYGclVnRpqb2p2BC+trPkCemv6Tts3gWFDX+zRwdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T11:44:00Z"
    mac: ENC[AES256_GCM,data:LQmmK7wDP85i/NvcDNi16gUIpyGtIzY+ohmJ31CYR0pApVswntnYysmkrJoqM6pVZOp8/Zp242nC7q7FK5VW9grUoCVew9loo9E27dEaSz/YMl8ZDVsc0+wITf8Gr+h3+3BIMuuShBLTRKlsaF0qdsnGpwJpyo139SLoxbi1QV0=,iv:HHgrmQ6Y09KgPC4si3wfq+YnxXgR86fjSrHbZQ+gmLM=,tag:rKpI3mGzM8zf4jiixc7N5A==,type:str]
    version: 3.13.3
