apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: forgejo
      version: "17.1.5"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system

  values:
    replicaCount: 1

    ingress:
      enabled: false

    service:
      http:
        type: ClusterIP
        port: 3000

    persistence:
      enabled: true
      size: 5Gi

    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false

    extraVolumes:
      - name: cnpg-app-secret
        secret:
          secretName: forgejo-cnpg-app
    extraVolumeMounts:
      - name: cnpg-app-secret
        mountPath: /run/secrets/cnpg
        readOnly: true

    gitea:
      config:
        server:
          DOMAIN: git.lxft.dev
          ROOT_URL: https://git.lxft.dev
          DISABLE_SSH: true

        database:
          DB_TYPE: postgres
          HOST: forgejo-cnpg-rw.forgejo.svc.cluster.local:5432
          NAME: forgejo
          SCHEMA: public
          USER__FILE: /run/secrets/cnpg/username
          PASSWD__FILE: /run/secrets/cnpg/password

        session:
          PROVIDER: db
        cache:
          ADAPTER: memory
        queue:
          TYPE: level

        service:
          DISABLE_REGISTRATION: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true

        oauth2_client:
          ENABLE_AUTO_REGISTRATION: true
          USERNAME: preferred_username
          UPDATE_AVATAR: true
          ACCOUNT_LINKING: auto

      oauth:
        - name: 'authelia'
          provider: 'openidConnect'
          existingSecret: forgejo-oidc-secrets
          autoDiscoverUrl: 'https://id.lxft.dev/.well-known/openid-configuration'
          scopes: 'openid profile email groups'
          groupClaimName: 'groups'
          adminGroup: 'admin'
