apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbird-tls
  namespace: nginx-gateway
spec:
  secretName: netbird-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - cloud.lxft.dev
