apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kube-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: https-id
      port: 443
      protocol: HTTPS
      hostname: id.cloud.lxft.dev
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: authelia-tls

    - name: https-netbird
      port: 443
      protocol: HTTPS
      hostname: cloud.lxft.dev
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: netbird-tls

    - name: stun-netbird
      port: 3478
      protocol: UDP
      allowedRoutes:
        namespaces:
          from: All
