apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:HiMtWhuG8aQJQs2AwGBEJU7eSdL10bcTLHG/r/jVeCPLd2wahCxNkCr3e6wOV9/wdMwOUtw=,iv:QjIvRWte8883hj/60Q86N2cqFgZOMMeIf1lxz6Wr9JQ=,tag:uTCBm+cR/RdFwTSNt9Jhng==,type:str]
sops:
    age:
        - recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQXlsdnBYblhDK2ZRbUZs
            QmV3R25jSVFGU2hsKzc4MHpMTnF6RzI4Y0ZZCkphcDJIYk4xZW52NHI3anh2bFVN
            NmpOeUJhbGdkSVkwMEYwR2dqRUVyaWMKLS0tIGVodm9iWTllNFhiUktJSWtoY2FI
            dkd6R1FKQXVjaDR4U09Ib3kwam81N1EKlEp5XpFj9zJNrRSPLNGH86+NGJiV6M5p
            3KlBr5LC8pNTP1I6OiKcGGFpxhGc0X0dJj3CsMPPA83qXSaTbOd6ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T18:26:04Z"
    mac: ENC[AES256_GCM,data:tJsMiLE4vOlxlka2x15e9PKs0virtJDQrfkwdSrk/DV0pwh+ysoBj8/TeHipsDIf7l079RT30aJoiXh8nwGpG0V1eCz2zTw+fG7jlOOPRxywRsZ6ef+XvrhPdlRgfko6QFDOmiJazSOTU3LeoGzA+YhpPYluCUdEvnk7QoZ5iqo=,iv:L1ePC2xaij6uV7hfvgzwLtvznoDdXfku5aREAo6osQw=,tag:OUfxLtn+YrAyBEH8HkWsjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
