apiVersion: v1
kind: Secret
metadata:
    name: github
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:qEr1a7BkwjCCHF/O7nkX/L/7YhFkv3J6h0riei7qh45b9Ib+JCtQcwBr3eT1caSNqPjWG7+Z4noylhe8zgdiG8W52ROCUSrYbwy2mzA+4lGHvo93ePjjSgiUlMJS,iv:ikFEuFIqSgUfKom6Kt0V2C879muR9+9zk9DVayCesxs=,tag:IQmIuw2OvHzFEnWu+tKp6g==,type:str]
sops:
    age:
        - recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YmFyZVRvWUthQlp4WW9P
            czFjUmNDT0Zwb1YwUkJsRFVwRHFqWjZLcnpRCi9IUTBYV285d1V3Q1NFZlpNYXBy
            K0NsWjB6YmJpR2lPWWFvem5meGIwalkKLS0tIHFYZ0VCTmJXSHdaVFArNlh5aU4x
            OE1IQm5Fb2RXZndPN1BhQnVsR2Z5SUkKEq0L8tqpXeLRaMDCio62V10ohfqLyDAr
            ULdPfnhF8crJyhoKr9X6g8tGUX363oefjRAtuDehRuiWrYUHZmuZMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T18:30:10Z"
    mac: ENC[AES256_GCM,data:dU47fEdLXuGtyElFTlQoQrrk2TOHA/Qa7H8WAAymFH0qpgIJ9CZNn8co5pw8xCC/BWvAO+znsq1iFHOYCLAvBvuhTlOnU9Lz2kH6YNN+VEiDWQxADNLN7HONPNIhgUlXWvBiDlNE+L0pvHa5jTGLskCvABQwMPBFphFvEM0p3w0=,iv:bfThRY1P5DwYAOJHi3l7okRfZRJDlVH2L2eucPkRFJs=,tag:TD2tSVj1NXMQd8Yi5it4aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
