apiVersion: v1
kind: Secret
metadata:
    name: xray-config
    namespace: xtls
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:cKuUHmo1Xc8dqwu4a9fmDi2yGnD5KZX43o9uQgZPyc2XGBB6frwlH2LFONveGESNK+wFL3GBLENPOPgaICeUlfSir7ImFJdq1GoxS8lnjAIcV0kKSE3ScZABuXOE1pgn6VDe5CtSBYXm9k0FaucUkazmV09WVgpMY1kP8bwLcnYNGBa9lRoBUeGQwM+hlDUPd+HbEGKFqox1AJJmXkPbP73T8IVp35gcXF2y9lbnpukviRaT3t/xRWk6SWU0XqpwXLMMyXJnRN7LyaQOfDmLJIZuefZ45BqmlsYL5fFJRyApPCACfVuukDee5zxn+/lH3N7M402x3vu3wiN8+d5oa+l0/QFp6r0qrUhbp02NqOWXQFWtr3tpG4KVBrsBVkAwzv5YBdoQ/jlIA8HpeAHDK14KdaTrlmhC169LcNQT16mBLtwz7xjecMvqFHR/u0s2+Sj0QeGn/R7bYsO9Qncu6pjqh/pq0QUbCjOjXmWpqgSEh/U+KWy6y/RmJgnyaxvIreN0jplFMIy6CCdex2aar9AgSV4IpKK3G0IJ32mUr08iSXtdJSJgKKgA5aNyyJGKODXwhfAOm0+LSneufKHU+boBnbqD0T4mchiHcIh9uykQ4m7DSeVX8eOAinJmDX5AsfMKaI2P27cKL2g7L4DTDJHiVAtaZinduwA2M/9OVyZ8tdJ81IDrRk/2MBUvJ2ns1kHoddp73560bL3DAkHqBs5AuUheKNNVy4lYI0Xfy/T9BjB0tPunjq3QbUM+2PkDDgtca51wIXEpiRZbrM9jP29W7qog7krp6Pg4kHIz8p0nqn6wFfDjQkoutS2GNhzBbc1leed9po/1ydSR9fgwozZC3WHbphiF42KkKM1Rj6Yjq3mSq35ZxC8mIFodgw14PBKtEDgaYLQ5VSNFlFD3cDKIy7TnwabPX3ha/7JN2svpxh+rhVoRqP+XJx0SS8jYn4WyuTZQwPe0LNhNDXPSnVcu7bsm4THIzwy7nODGwHipw7KyYZDXeGmiKV1v+Escz//cvNmtAPImTBnHispVOyEmUE+kk+58YP7fH7j16nsmLNH71qiWRudSTOXSGJtQ1TXBOgsI7G0yFl7Y71z+sUSGDsFMx8hARIIOEuEmwMm3UgLzB+IHRiRNXZMvOSb0tcmc/ueRJ0NJoPjOsmiV4MLiFlqp0lyKTPggYt+0kOMpHGzOWi1D0tTCf0xMHn58imvFVuKZ2yDJ+T3L+cBS1SKibCoqDGbR8gk6U5Mlp57HI+oso7TlcVKKcYxTlsMjJC2fmSey3e7VA35+48Rh3NBsigV6uv7BjxL+vUEP6i/B0G8aNubvu3Rs9sP86ZjjH2q+B23oQY1AbGTDUDci+SjS9cVBOKLiBNnNdB/IkKz9dAaU+SzyfU8XHW7mPw4ZM+VbHfh4hPSkpBXpg0KnkdsKc5sQS8BXccT/fepTAl7dhXdVBBgDZLVh6FOfXq5FBwzBKCs7SY2QkwZrcl0wVyLicWmbSMGGWFsn7SV/PJ47/sfUGNTXdBKfnz/IsYsq,iv:hotxcSqq8e5R3Nw6Q2KZZHGQ2AGN8kEXD4436WD9rVQ=,tag:BXc5L8vsFDZp4bHy/7nTxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQzVWdHlNb3JwVCt1cmQ0
            RFZXSFdiYUN6Z0UvSFJrZ29JamFYZS9DZTJzCjJ2WTREL3R0ZWNsb25ZSHdyR2sv
            SDkzdm5OY0lCYlhvaUsydlFhaDMwTDAKLS0tIDBBc0k5QUdWcW94bzNEM0VCb1FJ
            MStNYTZ6c0NnVklMeDFGTHBpb0Y0MG8KBeWWQ2tD8q7SFKf4BDD7JMEDxqZIG07k
            0Whin8vgF2gXa9tEm6mGETtDGU20ycrlx2tAB01OB8i19kFEtWNRvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:21:59Z"
    mac: ENC[AES256_GCM,data:I2sGXwIM5QM4PzHE0cU1Ws9AAlGXXebC+MXLb7XR/Sm6KcLu5webFseCdJNDuPKruxNtuDjIxv8HgnYVMJ2V9jZ8XlgOGghfJ4wzn53cdKauV7dVfyqWdbDm6TIMXcNEkbusyLLKDVApqnkE40dnGj5BC2/Ih2n7UIawekfMFMo=,iv:PJJpVsVvWqLFccqIcOgy83aXvkzyOnR/C+SLdBNfbZU=,tag:bLetUFyqKdYX/i9pVYsHEg==,type:str]
    version: 3.13.3
