apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-creds
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Rpt10/V+vGxp1aeFW3G+kP2jcP7iAQVzuyiIOddABKtffbG//rnMUHyUCpjMH8VEnXqOg50mBzA9u6jZ7Y/c8TZuQzrRGsXfqcAyZKtmSWZj8LZa+ccEXNUyEXE3I8pSxBjcqISKHpWcwBvoP/B8gzfAwLZrdsg+7aU9yAA5x7sETuTWkLhciuPsfzAd5aUwJX5ltx+syf064wQ0ZEoXQktxNHxlZfsYQrsJQbbP8g/Hi4udEUJaedrffn5SoM425oQlEpEYYs3v/9f1eARx6/zcqnZmpgbXSvhCWGjcY4FJ7rPh38Lck8hsc+SiKl+dNdyLueLpvWeflY2rRWU0a5+7KcWlVWE=,iv:z61EmIyciSKgMThZHcWjjPra5+LiEandL94UwvPmeJY=,tag:5OXc+i71Y0NFc0l2FhcdXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RVpQYk93L2ZRU3drUTFt
            VkFGUFQxRmNDa0lhdGZGMm1iRjRoeGkza0c4Cmo3L20xY1BJZHg2M1hYOEl6QmFn
            MzV6UlJNbCtRZ3ZUbitoeWFpYlU0M1EKLS0tIGljdXlHcEkxU1QvbEQ3dWxqZkJG
            NCtySG0xY2tRYjhkR3hINWdYMTdFRWcKhK2n6G2K1Gw2alMQe5UMb+5LpLxURdYJ
            c8j2xLnpaZuKG4zh0ecm8DsnvlhvoBJ4L7n/DJkAsP6sdHM75spavA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T01:21:24Z"
    mac: ENC[AES256_GCM,data:O5XB9Kpf4I0DQnPNgRbCMCKrQp5qcvK6PY1qsTg6zilYc03YLwSLnPvcT1gf6t2iJeBXfkFCSTSLCLeTgDjJHiH/yUTU2qHwRW5tBywfQvNT8NPDV5FeX82XUBk6aYE4sylBPW8zxqWzWFVsucOlfLSpY/HzMfw7PvX2pDsLwD8=,iv:M6nJO/79VnC0OPQPcoHiPsH8iITFPnxJlCaxcy/gFxo=,tag:j3v/ZnKQ/yfMyR7mQ/G7mw==,type:str]
    version: 3.13.3
