apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-creds
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:rYyhBz3rOpjmfktGRjnGfERDJp8AzJ8cZgVshfiIv3OpKEZcatRQd5eMgJNHvfPwW/yrjFfDzo4B1uuUquG15jtGjS44GkobEkOvqHn22ZxdtbEOYRZv8mL9P/qw7osa5ECrhZwLmrPiaVaTqOWQiFPI8NFdWGb1a2q7aCp9QAJSc502GBDFTQ/BlPV42ocCnrdVtZLtPihRmC9FvN0NS0e7fKgr/eWWDwIadiThGSbYWD38wTmPcdn1wFrKXoxF1mlHq3HgKOUKEvoso6/W28fQYwamvg3xMMXSlfaw8deqsmXLsOUob7YnVV7bYqlcAC8YtZFztipRLrmkmhYJCkQJS4wY7mHTe6mHgtC5,iv:hITwzB8E84CEONedzPxsSOtCHz72MCiBCOaA1L7pE/U=,tag:d/Vb5d7IkXeBaBLDGY0B9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc1E2N2IzQ3dCUitCZ0Uw
            U0pwYTF6SUlqNDJ3VlNEbGZLMngxMU85NHdNCm9YdlQ0TDAzcXpoakxGV3ZoYnB3
            dHBYK1JlVTJhbUZRR3VENGYxNXZqN00KLS0tIDlpN0pXbmxWeUlNZ2ZIVGsrNkdH
            VURKb2lBWktYNTBNaFZzK2FMUVdEZ2sKjKnrfG6LrfcTUR/GDlJHThW2tspEhlB1
            5J4lTUkqTW8eW+39L+1Vynu0IQzEyp1ELW+S/FvjI4bmA4BciJ5OZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T01:42:05Z"
    mac: ENC[AES256_GCM,data:EvFZz+a3VIcm4oGRHk35BM7CDF1XYyHeIGdH2BLWTZ19H/NsIdTTOEYaprjWIuxAucEbk+EVAcevoPxObawCXptdfn4hJO27lYzk3MOgPbhfEnHO/YrSO1NV0byDzT7h+J+TU2NnOZM6G2bI8RzMikV4+1BxVZeuL2pIYxfp+HQ=,iv:mY0Aap+CMU5tm6jCtmnIR+7tUCDyYK2C0P47IKkWo9w=,tag:KWAytreH8+Ji5b1EdBnpaA==,type:str]
    version: 3.13.3
