apiVersion: v1
kind: Secret
metadata:
    name: docker-creds
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:yPtFhI9TVh5WlCQ6E2L+az9tTByd27isUWFocoWcR/OHxkugUsyASIZr3QqOvY5pZeb2Ad6KwjzMI3AzQZ5hgggO1p9UYFMG+JkolcACNK7d62x5mrk2bLAQcaNcR8Smp3Qv6eM0cvTIOp7EyDdSxTv/IBPYXa3QgO7bfEiccdFaXHmtvz0Ieza9GVhmvGFJMfIkEKpXqvD6Eh0tpFv94U3+7gXFHBjkrftaaASrpFqXrDQPpPdjFR2P+U0VLMPW0exfB/8WUKnbIMiWsw3TcBqsIzV59GeWybjwnUopqzxwceYWHm3FLsQg1F83P7L+t1nfxL85NAwyU1DhRJ4E3ig03tfxvr5tbcxAAdEF,iv:WRwZ+JFn/ba8SRmfZqI7wnuThzACYDutZQisKB7NdNk=,tag:IfiTar5BQtN7TGxTpX0okA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZlF1alRzV2NETDcrQzBK
            cWxzMHVMbC9GZDd6US9qNnRvMFZGUExUSGxnCi9TTW11eWIzMGRUTXN5VFlNQ0JR
            cGF6WHh3OFczeHNpbStlS2RsNVZCSXMKLS0tIEt0eFRKNHVldnJTNGRuQVNTQWds
            R1NyTUpMWjdoVjBqaXpZcmdCTkFoSW8K7H05VtohSRU7AYGOeRIjkqI/fBr+Y45j
            BnmMf4tjFh5JCxYwUFsypKTL1YAwl9Lg7KmzcDA1L/FyTrju9R/neA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T02:05:12Z"
    mac: ENC[AES256_GCM,data:6fCEDumuq0YscvEHZrN1uCg7Y8mnCyB7UgNoHHjiM0PHs0yLV+V1XnklAYh/mHqCN5frETGtwoB4L0bXjhH8a7phRxx/c0NmwV7gWUZO3q/KwAUoGx6ipJtgd244yfnNZiWBfNSIH4N8Nw6+hFq0we2gf17OvSxbCa6saXJjClE=,iv:mchAtwm7ntVItj3T7nUZmkfTitWYp2AsR+JQ6TJkocg=,tag:YOYMkDlbq39Q24Y3I5YrAQ==,type:str]
    version: 3.13.3
