apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cert-manager-config.yaml
  - cnpg.yaml
  - flux-notify.yaml
  - envoy.yaml
  - envoy-config.yaml
  - registry-creds.yaml
