apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 1h
  chart:
    spec:
      chart: authelia
      version: "0.11.6"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    enabled: true

    pod:
      kind: 'Deployment'
      replicas: 1

    service:
      type: 'ClusterIP'
      port: 9091

    rbac:
      enabled: true
      serviceAccountName: 'authelia'

    ingress:
      enabled: true

      gatewayAPI:
        enabled: true
        hostnamesOverride:
          - 'id.cloud.lxft.dev'
        parentRefs:
          - name: kube-gateway
            namespace: nginx-gateway
            sectionName: https-id

      tls:
        enabled: true
        secret: 'authelia-tls'

    configMap:
      disabled: false

      server:
        port: 9091
        path: ''

      identity_providers:
        oidc:
          enabled: true
          hmac_secret:
            disabled: false
            secret_name: authelia-secrets
            path: 'oidc.hmac_secret'
          jwks:
            - key_id: 'main'
              algorithm: 'RS256'
              use: 'sig'
              key:
                path: '/secrets/authelia-secrets/oidc.jwk.main.pem'

          cors:
            allowed_origins_from_client_redirect_uris: true
            endpoints:
              - 'userinfo'
              - 'authorization'
              - 'token'
              - 'revocation'
              - 'introspection'

          claims_policies:
            netbird:
              id_token: [email, groups, profile]

          clients:
            - client_id: 'E7Aku2J-60CsjZx0YCE-5k3aQ45s1n8-gGuh1UNuNnKM12maJV_1SwHNwvqGmSfhHm8wIB0w'
              client_name: 'NetBird'
              client_secret:
                path: '/secrets/authelia-secrets/oidc.clients.netbird.client_secret'
              public: false
              authorization_policy: 'two_factor'
              redirect_uris:
                - 'https://cloud.lxft.dev/oauth2/callback'
                - 'http://localhost:53000'
              audience:
                - 'E7Aku2J-60CsjZx0YCE-5k3aQ45s1n8-gGuh1UNuNnKM12maJV_1SwHNwvqGmSfhHm8wIB0w'
              scopes:
                - 'openid'
                - 'email'
                - 'profile'
                - 'groups'
              response_types:
                - 'code'
              grant_types:
                - 'authorization_code'
              userinfo_signed_response_alg: 'none'
              token_endpoint_auth_method: 'client_secret_post'

      authentication_backend:
        file:
          enabled: true
          path: '/secrets/authelia-secrets/users_database.yml'
          watch: false

      session:
        name: 'authelia_session'
        same_site: 'lax'
        expiration: '1 hour'
        inactivity: '5 minutes'
        remember_me: '1 month'
        encryption_key:
          secret_name: 'authelia-secrets'
          path: 'session.encryption.key'
        cookies:
          - subdomain: 'id'
            domain: 'cloud.lxft.dev'
            default_redirection_url: 'https://id.cloud.lxft.dev/'

      storage:
        encryption_key:
          secret_name: 'authelia-secrets'
          path: 'storage.encryption.key'
        postgres:
          enabled: true
          address: 'tcp://authelia-cnpg-rw.authelia.svc.cluster.local:5432'
          database: 'authelia'
          username: 'authelia'
          schema: 'public'
          timeout: '5 seconds'
          password:
            disabled: false
            secret_name: 'authelia-cnpg-app'
            path: 'password'

      identity_validation:
        reset_password:
          secret:
            secret_name: 'authelia-secrets'
            path: 'identity_validation.reset_password.jwt.hmac.key'

      totp:
        disable: false
        issuer: 'Authelia'
        skew: 1
        secret_size: 32
        algorithm: 'SHA1'
        digits: 6
        period: 30

      webauthn:
        disable: false
        enable_passkey_login: true
        timeout: '60 seconds'
        display_name: 'Authelia'
        attestation_conveyance_preference: 'indirect'

      notifier:
        disable_startup_check: true
        filesystem:
          enabled: true
          filename: '/config/notification.txt'

      access_control:
        default_policy: 'two_factor'
        rules:
          - domain: 'id.cloud.lxft.dev'
            policy: 'one_factor'
          - domain: '*.cloud.lxft.dev'
            policy: 'two_factor'

      theme: 'auto'
      default_2fa_method: 'totp'

    secret:
      mountPath: '/secrets'
      additionalSecrets:
        authelia-secrets:
          items:
            - key: 'oidc.hmac_secret'
              path: 'oidc.hmac_secret'
            - key: 'oidc.jwk.main.pem'
              path: 'oidc.jwk.main.pem'
            - key: 'oidc.clients.netbird.client_secret'
              path: 'oidc.clients.netbird.client_secret'
            - key: 'identity_validation.reset_password.jwt.hmac.key'
              path: 'identity_validation.reset_password.jwt.hmac.key'
            - key: 'session.encryption.key'
              path: 'session.encryption.key'
            - key: 'storage.encryption.key'
              path: 'storage.encryption.key'
            - key: 'users_database.yml'
              path: 'users_database.yml'
        authelia-cnpg-app:
          items:
            - key: 'password'
              path: 'password'
