apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: authelia-secrets
    namespace: authelia
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:eB/pu5bBfy0gVB1OSCP1lvpBNnerST5BADf/UvhiJF0jpyhSJrWULvnOJpZ7jBQz1BqBjcfw6qBarjvZgNlXw5yEY03/u3DZnd5vB9l6wQRf8REM4nkRKF/rXxLskN67PztfDvtNN7NOuexzJFGZ0ra3Dmlegjh+RYYzZysbLPU=,iv:8N3P4Tn6W5R/gKhM/exYCX7qLWA9IglPB8WyYHtTfJw=,tag:t5ZH/VxNqe4PXdBOPR+mKQ==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:50riy+Do5iU9zCGBzhw4hR4p55sjyOSJ2fX71t0nQXiSPYZiGMnefN/vq3fgCA18QqmpBBwAIUXw7hkfiAYmp3k1Fdgj2Rd0RAznhxtJ0pInT+eRXpIOfu2xSKfKswZaTN5Plgfxj29vIM8DHyNJtRUq0MRt7Tf9U0dyrr2zWU4=,iv:KCRJO3MZaEwlN4Z5DBLw2r999dx9pGqrrxokUNV7YcY=,tag:rnYRFKMmjimtxIl84x09cw==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:Y6wbFAhSOJIloVokhrKd6ys/1mkIU9jOFMY2iwg1kXWS+LBDPBA8pqsw1DMYa/gIhWjjD9cMomWXDUhODDjWkBg8yHOrwrGUB+JMQeeDYASS90ecEDWJDIv/I4n77kNIdsfR3/7S8xQXxpOxW+O/adBLc4ipLG3Ur1QOAHVpwTA=,iv:UogK30YIy8vVtzbzthpercioQkKVGgw5jlaGLta7z3g=,tag:E54cbHE1SgCXOKkWAk4siA==,type:str]
    users_database.yml: ENC[AES256_GCM,data:W5l4uOnSZ6TucN9EIEpNOZmgjW2TX6QR+rGUP0qTWLe5UqNBLvH+eAnEiTIvI8KEfHtRns+YSCHQoDG42qzO46IBmjY9GrxQSd6tzRjsZWAmJwMrfTKzmAcVBx2NFqjKF69fFjlN0NBHjdF4i51DNHRd5Mphi+2Sd1bD7QtS/169sLjE0IZ/df+KM6DcQeMvtb3ddcBY8E7gJw+cWtMFWHay6Bv2b6n1JfcDpUmC1NkVEFrh7xjGAZT1tHStASHVfNn8+yLFyxCaar9Xn818g2b6mBJRpaVEhkt8TmKg1Y4spSbRsp3SSSXmHQXWRpeGINmFOfgbeQn8LDik7k3PjU81T70=,iv:s/WKXLf3y5gtR6NaXrxF9YNp20yJ0BHtE7P30m9q6A0=,tag:j5Af+mA1ckMg2PuxH5YGBA==,type:str]
sops:
    age:
        - recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L0ZUWUphQ3FoTEpDTCtp
            YkY5ZVgzUlhxdTZmTzlzRmwyL2plNGs0UkUwCjdETloyU2hpbnJOMUJLNGpONGxB
            TVNhZGxqbEhEWUJuQ1FIRGJxejZYQ0EKLS0tIEFrdkt3eFpKRGJ6VDFVRVA3Z3ZK
            YXFna1hiOXhVVXNtNWFBTWg5aUJ3Q2sKjIuFVI1s/NVWeLJ8WEZ1KeTCPqfJ/qX6
            LOqkLIdQy2Rw53J5oBtIa/FfVprr/nMb8MkrKEcdXUjyFuzpoFK+eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T11:03:16Z"
    mac: ENC[AES256_GCM,data:uGWbeogygSq+bfUsIa0nFNzo8YLVAn4Z+OCsAbpQfJj1CwDryVICIurVbqNHlR4g8myiTlutByh/ztdwX0loMwqVexJeu3up8L3vGXkMo7W1YGI42OtetDIsYnHS3tXqw7wU303rpxfq8U/Z7HE2xohDyX1KVUiV7v3hhgAhvck=,iv:NFPqg0EYwef+T6i5d5USxxIcqJPJgqLlUHXWa7f7w+8=,tag:CdbgXmyS4GEwqwN5S3W+gA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
