apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: authelia-secrets
    namespace: authelia
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:mhkGY1h4ciHoZqCMpvOstW7k2qpsHWvEAy586EJAizaKAHrjnoT8Om7+YWz5+KABFBO8q15XT1qf4+DoX+uCjkA6i2pMTjNxr3i0mZDIgTJ67y7sw/iurR1vYjQIKtQbiK0uy3CMU3BUuFy87NsgYkZLQ4tFSMsR6R7nqUV7uuWLr87nke//PJwg/wx4mNlsSCdav9DG+Jl5fVOuxZ1+XXB84q9ShBedjZV7BAr+xGuAH82J5uX4EhkADR7jJ1yhlPDrngfOOiXSdOAvkaRCy+ppFqzUaDjfQK3HosB6+uUog4hfq5nTFk44qKXVqVU3gmGKgL5Q1BDdRc8FNeREgg==,iv:o3ApOroAR9+PfaXdedCG5acBKdbVtxdbt+mhFIt53uM=,tag:EUPzeAKKMyN844VHNsTDrg==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:LWK8fuG03oONIdGBlWjPuBImDjBXVoDz97LtiRJPuLpNmLnsWCtdgZuKCBGxU29st6bIqYNDO2jcC2uuMc6ag/+5SJO6whb68AMiMdEKyR9Q+qOG80G4V1Ogjn9gMruTrurzzzdMzq9Xv8JvgaZpQkKBMtZaelOw4Q6tRT1JA+9umnQSeeq+RN1WlueTR3SxwUFBWXdwMuejY/8ezqelstXZl9EVscx6tYBMRqnthkwzQTtknyN/3IukfKx7G/6R9q38xdNScptvTkPl+8MHuraihedfXNaxeUn4J8Ci1uzK5MbUTXkYWGfeLMfG5d9RRf3a/LVbu1B+0oQ0OIsalg==,iv:E6KZSI3wHMVOlofU9pP9MEci6VD8iPYx14PmIm6ji3U=,tag:XhkKe/+9+7K+GrBzFBWTIA==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:m/NxGdTtQx2ObPKV7pPzDAkk1lAHTBEW1hJUqib7biTVgtcXqTjPpGyZ9cyKKQS7EJYRje5dvpEIkU7HQDv7epucoV6Ag1HZkROWLTqVHGZ2X0qU2KRjY4K3bMKyUBQBMmfD5A/r3xwVK8zXBH010HDXBT39JD1ddZ6x0+vdANkVOLU8zzn/kWKaW2VqqZM4rBR69FZbEYGpZn/j8Ddd/cFSWUNCr1u9JHxNAU2FkF1qbt+colZYBEnlxl5AlLFK/x30B2rxOqmyz5WKHuPXash+2RuWz14UwHFEmrnmLBIpQNessyxGysSGcCshOLz5k+9Z26eZs1ySuSNsjUCMQw==,iv:8ZYne+8gFV7NzVklZMpYntWdOG2yOE8XEOuQ9RWiSFQ=,tag:UflTsd/BGsnEG5ADdscBiw==,type:str]
    users_database.yml: ENC[AES256_GCM,data:Ea2IUXPah3ftiHdelmdHYqCiTZryNT/VTJBA/WtAi0/9rGNNwMpj94XeIst/F3I2Pk7U8E+qRkEcCXdTSSjfVZUwms3pr++AyNy78VW+l+JtyF/lR9mHORkxXePrtCxSQhnQ+r4pD7YDGAJDh/gwU0xAYo1Br1faudxVwZk7ZHF9oFBJcfp/8QyjLmhS+pHT5OgB0WYToXv4XX6GmxvjIJjvWVKd4yFNH2Ryh35R+1Gxe3jVI4Upl9iRCVMDLHz+1vv4z0H0oH8d+iAKXvBgWq8Bw+OtpVtd7h7TSmYyl7XS/eP094YAEHLlNRO3ERtfwAmDGyOUxTRlsODKbDCPTk4=,iv:+vQ4uxEDadURbQzQiAgkTyj5Msc8zLgd3h72e7cb3CY=,tag:MVVIPwlQjK1V04+JOTJlSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZWtHb3IwTWNMVS9kL2JJ
            WmUzOUFVY1FORk9nYmpEbTFUMHBKbGYwQnhJClg0WjNVSi9jWjVobXBReWJxelcv
            MWFNRnJ4MlVURVNtWmlORmcySFZ1V0UKLS0tIE5CeTNEeWlpTGhFUEhjS3ZpQmRp
            UGNuYkQxK2pTZ1A1dUZOc0tCNkhPdzAKtoGzcUrLjPBZO/U672tsf92UgHyOCBK3
            kjRhYw4VtgQUQ2+JH/ev2x8CW5EM83J69QG7niRY/473LrztHRkEiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T18:42:43Z"
    mac: ENC[AES256_GCM,data:CaQO5enI0ECTnyiUN7FZWRmfdwyAyJDvum/mk3gZcKs4gc/+o8jak2XjOJDynWNL9/UVinUleBg5HlP9rUg5aT2HvoP7pmJJ/EPuuvd0+BPHQPfpn43pxSa/CzBqc/KsrSCzgQzrwbg397/58Q9Q8+eTpbPXVqf3nuJBfEsjkW8=,iv:SZjsMWRpfADuQ7ygAYdzSdf1+mKd+b3/8gTMfYcPdCM=,tag:vHMiS+I601n53y0B8ZpvfQ==,type:str]
    version: 3.13.3
