apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: authelia-secrets
    namespace: authelia
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:hVZFpKA5umFONgh8a1o339VFJZWIjv4mXl5r5ui679iWq+WueNyIQBl86uamtQgveSjDF+VXuO0WLoG9zJ4k/XhjsJCi+Lo3tQTa32Ukw3kVSYlITJkT+rniOD5CbHpA3G0DRxrmbdeFriFn96Lv0HUXPkyIPrZULVpuTrLsP3K/udc9mmE534WMNrKa0kd6oIxvmtwF05GV4g8rnIozJwgqQTsIgPvtcfL8Ij7yC3Vfv+IybD1K9ymDjq7kf/BRW7BN6bPGpFSGtS6nKmdodj4t4N5z8iWhtXO24Dxb5GMX/H0DhbYUjWHmWiER4jhiK4oOaidXVdtgGcrLA9fbHA==,iv:vcDDFSQDITdUnL9fTsxmDNevU3Uku/nfgU3dVqK2Jyo=,tag:e9A++Sjk1CODVWDdivnTng==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:f6EATRt67Ke5PztombayXC5rA4f9bB148lcdfQpP7xHo0DJ+fl9F3BK8L7A6TiSX7x9LTioo6deYud2lbjD9EB+Da0gSWojAJdCkT0qhGLAXMwHyuSBvxzg3/Y93GhK6ydeLzO6bn7zHdNpJLdgDjXXqdruRe0PQY2lCfw24Iwc1AWc6s1fvA87AXBhUfHufguqjSBljpEchCZhP6NXUXK2OZWXlUMbA6EVO+lQYSee+OsXEf9EQBiBbVEhxCV/U1+P4Zc9yLxtwLNKH7+GDMyoOQZ8RJjkcVAjvjIkh6vtjvJA/X4cEygsroEOVBKRmGOAIuslDCmAjwBpypk/lMA==,iv:Iiu2RsyPXR9sxR1bYvX6ds/VJ0S4hTevN3Sh5cK5QrQ=,tag:zT6N4Cq8/BTUAq5mq5x93Q==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:VAwHiPNLpEkvkICwz1uZQa7GXKcC6pYudWu+2Qq3yganBBVY9zIPcmfBlxVP/Q6FI9yTAdo++Eq1leTJ+DBU5J4qvaM5K5MkXYkEdHrz6KsomdTwIrpEhqgA5De5KHwgLzzGF3lPyRCW1JVduQUQCC5l/OTW/5kc3SLdG8qHyU0YYVxpIfII5xmxrfn7Y9z6ryWJLnh1sZQVjl+czauf1Z0Tx586ZJHSz2S493OHKLiSBxoX2uECnizL5PnH/DwjKfWOU7uOB3dg9HehsaYSNUADLu/ixwcEjCPHyugKvPh6NbKBuvPgvd33OYvN0ORAC0aWSb9u7/4IYXh0qmRmTA==,iv:v7QHMkwIHGQ8i56u/B0991PdrQH1w9iY4QToLweEkhU=,tag:Gi784kQD4pjTQyqRNFhFfg==,type:str]
    users_database.yml: ENC[AES256_GCM,data:tK/EETMSQJjZMBiBbBtgz4kXXSU50qItw7byPVPACT3fA/qYYLBLfRmaBXzVQ95Ghw6kXWmKoaojH29/11zW/pGuhac7CHRHuPcZLTeu27k6/rVlsUZFOIgkumJAcIC6b1ttq7rflBZQnR5Ezo1DbWWZly9gqa0+Wo8kZ1KGSR0iHqsNAeAefZVft2RL5w30i8HIiX2RqYhAeZxDUVr9zyJfciJ68ZP7Nvdy7SeMSif8ye60CpVfN1XyaJXlBlTcCj8UV2kbYCl8B+u55Kbd1jDwelb5pCg0fValRh8j1mYGo50Fx8KBFg1PotmdifrDddL7WksI/p7O2RDxp6UkocA=,iv:lUVa0qlWPnxJmWpMRW8k/Ue0p/4IsLoSJxUyVVq+epE=,tag:U0FdPk7QrQgvgAthdHjdFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcDlWOVJUY3dTc1BaZEQv
            ajlWM1N0SHMrK2VPNithS01EanpaR2JkRTNJCm1OSjBVZmpUV1c0SW5idlFNZGZC
            RUNmVmpzMEFkaXFaVnhzankxNFQ2RXcKLS0tIHQvMVIxVjFtMGo5dlZaRCtFaEdY
            YTlhK3RtZmtSWjBvamUyb0JEN0NPRWMK9fBBhBknot24YccVRgHd5B4jyvkrX32u
            EvYCIU09Q4uIIaEynPJpEKZkfWd6fc0L7HUoftR+gL/U733WtRsJHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ls48rmxmku53u7kck47quchvql9ktde58zvg60q7esgk9wsmwfzqe4ldya
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T18:47:33Z"
    mac: ENC[AES256_GCM,data:fLszGDf0Lj/BwKgIdHk48zdmtQjGhI/xCyvM5t/eAOcrZVZCQ2lXw8Jzme9ilsBYCms85rf2+3N+EvOLrlEx7NXmmg9YaW9FrDB42JzG7AOfVUO1jBjmEp+eWZTWtqxrZ1WB3p6lOmPrMz/PAMWORi2/gBKNxMlERZxHxtjOn20=,iv:ATfGlTYYDj41zn7b1b9paOOvtTk6lgiZ7rHNuU4r8zI=,tag:hoLugjW4j4JKNgPYCFfV6g==,type:str]
    version: 3.13.3
